platform:ios,'8.0'
target 'YJCard' do
pod 'AFNetworking'
pod 'SDWebImage'
pod 'ReactiveObjC'
pod 'MJRefresh'
pod 'SignalR-ObjC'
pod 'BaiduMapKit’ , :inhibit_warnings => true
pod 'WechatOpenSDK'
pod 'Masonry'
pod 'YYModel',:inhibit_warnings => true
pod 'MBProgressHUD'
pod 'IQKeyboardManager'
pod 'UMengUShare/Social/ReducedWeChat'
pod 'UMengUShare/Social/ReducedQQ'
pod 'UMengUShare/UI’
pod 'UMengUShare/Social/ReducedSina'
pod 'pop'
pod 'Bugly'
pod 'UMengAnalytics-NO-IDFA'
end
